export type RetrieveACountOfProductsOptions = {
  shop_no?: number,
  product_no?: number[],
  display?: "T" | "F",
  selling?: "T" | "F",
  product_name?: string[],
  brand_code?: string[],
  manufacturer_code?: string[],
  supplier_code?: string[],
  trend_code?: string[],
  product_tag?: string[],
  custom_product_code?: string[],
  custom_variant_code?: string[],
  price_min?: number,
  price_max?: number,
  retail_price_min?: number,
  retail_price_max?: number,
  supply_price_min?: number,
  supply_price_max?: number,
  created_start_date?: string,
  created_end_date?: string,
  updated_start_date?: string,
  updated_end_date?: string,
  category?: number,
  eng_product_name?: string[],
  supply_product_name?: string[],
  internal_product_name?: string[],
  model_name?: string[],
  product_condition?: string[],
  origin_place_value?: string[],
  stock_quantity_max?: number,
  stock_quantity_min?: number,
  stock_safety_max?: number,
  stock_safety_min?: number,
  product_weight?: number[],
  classification_code?: string[],
  use_inventory?: "T" | "F",
  category_unapplied?: "T",
  include_sub_category?: "T",
  additional_information_key?: string,
  additional_information_value?: string,
  approve_status?: "N" | "E" | "C" | "R" | "I",
  since_product_no?: number, 
  product_bundle?: "T" | "F",
  option_type?: "C" | "S" | "E" | "F",
  market_sync?: "T" | "F",
}

export type RetrieveACountOfProductsResponse = {
  count: number,
}